"""empty message

Revision ID: 3ac8fd3ac52a
Revises: d16a963059da
Create Date: 2025-06-02 08:06:24.323516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac8fd3ac52a'
down_revision = 'd16a963059da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
