"""adding ondelete for all

Revision ID: 40781bf364b2
Revises: 88d8eecaa7ac
Create Date: 2025-05-22 11:37:45.783702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40781bf364b2'
down_revision = '88d8eecaa7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('article_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
