"""removing stripe_customer

Revision ID: 4442301a51c2
Revises: 951015727cf7
Create Date: 2025-06-02 08:38:23.197977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4442301a51c2'
down_revision = '951015727cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('subscription_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('subscription_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###
