"""adding stripe_customer

Revision ID: 5754f467fecf
Revises: 4442301a51c2
Create Date: 2025-06-02 08:40:55.057740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5754f467fecf'
down_revision = '4442301a51c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=256), nullable=True))
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('subscription_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
