"""empty message

Revision ID: 6235bb65494c
Revises: 8782417ec695
Create Date: 2025-05-22 12:35:29.267342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6235bb65494c'
down_revision = '8782417ec695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
