"""adding __init__() method to all

Revision ID: 7185ec9783a8
Revises: 159b78c3b912
Create Date: 2025-05-22 11:11:48.632073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7185ec9783a8'
down_revision = '159b78c3b912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article', sa.Integer(), nullable=False))
        batch_op.drop_constraint('like_article_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'article', ['article'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('article_user')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('article_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('like_article_user_fkey', 'article', ['article_user'], ['id'])
        batch_op.drop_column('article')

    # ### end Alembic commands ###
