"""empty message

Revision ID: 770f6a4640b2
Revises: 6235bb65494c
Create Date: 2025-05-30 13:56:52.916841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770f6a4640b2'
down_revision = '6235bb65494c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
