"""fixing on delete

Revision ID: 88d8eecaa7ac
Revises: 7185ec9783a8
Create Date: 2025-05-22 11:23:27.747121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d8eecaa7ac'
down_revision = '7185ec9783a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('like_liked_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('like_article_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'article', ['article'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['liked_user'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('like_article_fkey', 'article', ['article'], ['id'])
        batch_op.create_foreign_key('like_liked_user_fkey', 'user', ['liked_user'], ['id'])

    # ### end Alembic commands ###
