"""fixing string id in customer id

Revision ID: 951015727cf7
Revises: 3ac8fd3ac52a
Create Date: 2025-06-02 08:13:07.832477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951015727cf7'
down_revision = '3ac8fd3ac52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=256),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
