"""fixing bugs with customer_id5

Revision ID: 9a7585a18cf0
Revises: 5754f467fecf
Create Date: 2025-06-02 08:56:55.457706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7585a18cf0'
down_revision = '5754f467fecf'
branch_labels = None
depends_on = None


def upgrade():
    # إذا الجدول موجود بالفعل ولكن العمود id ليس autoincrement:
    op.alter_column(
        "stripe_customer",
        "id",
        existing_type=sa.Integer(),
        nullable=False,
        autoincrement=True,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_column('id3')

    # ### end Alembic commands ###
