"""fixing bugs on liked_article to stop the name errors

Revision ID: 8782417ec695
Revises: 40781bf364b2
Create Date: 2025-05-22 11:49:36.960394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8782417ec695'
down_revision = '40781bf364b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_article', sa.Integer(), nullable=False))
        batch_op.drop_constraint('like_article_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'article', ['liked_article'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('article')

    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint('stripe_customer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_customer_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('like_article_fkey', 'article', ['article'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('liked_article')

    # ### end Alembic commands ###
